name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Executa uma vez por dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        id: snake_generation
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to the output branch
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git clone --single-branch --branch=output https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository_owner }}/${{ github.repository_owner }}.git output
          cd output
          cp -f ../dist/github-contribution-grid-snake.svg ./
          git add .
          git commit -m "Updated Snake animation" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
